const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const ADD_TO_LIKE = "ADD_TO_LIKE";
const REMOVE_FROM_LIKE = "REMOVE_FROM_LIKE";
const ADD_ONE = "ADD_ONE";
const REMOVE_ONE = "REMOVE_ONE";

export {
  ADD_TO_CART,
  REMOVE_FROM_CART,
  ADD_TO_LIKE,
  REMOVE_FROM_LIKE,
  ADD_ONE,
  REMOVE_ONE,
};
